### PR TITLE
Added Matrix Script Problem solution, problem definition and explaination

### PR DESCRIPTION
**Pull request by SatyakiMandal**
Problem link: https://www.hackerrank.com/challenges/matrix-script/
Difficulty: Hard

### CODE REVIEW

**Review by aryanargupta — CHANGES_REQUESTED** [review]
Exclude the question from the comments and rather cite the link to the question so that the direct focus goes on the explanation and code. Try adding multiple solutions in a single PR in future.

Good work with the explanation thing though

**Comment by SatyakiMandal** [comment]
Thank you. Will keep that in mind.

**Comment by SatyakiMandal** [comment]
Required changes have been made.

**Review by aryanargupta — APPROVED** [review]
LGTM!

**Pull request merged**
