### PR TITLE
Super Reduced String Solution issue #4

### PR DESCRIPTION
**Pull request by rishissahu**
If anyone having any doubt can ask.

### CODE REVIEW

**Review by aryanargupta — CHANGES_REQUESTED** [review]
Cite the question link, and give a brief description/explanation of the approach taken into account. Rest everything looks fine to me.

**Review by aryanargupta — APPROVED** [review]
LGTM!

**Comment by rishissahu** [comment]
This PR will be counted in Hactoberfest or not ?
As of now it is showing Not-Accepted.

**Comment by aryanargupta** [comment]
> This PR will be counted in Hactoberfest or not ?
> As of now it is showing Not-Accepted.

You have to wait for sometime for the not accepted to change to waiting. Don't worry unless it shows something like "PR on hacktoberfest-excluded repository". Rest, afaik there's no such issue yet, it will be included after 7 days

**Pull request merged**
